language: ruby
sudo: false
cache: bundler
script: bundle exec rspec
bundler_args: --without=extras
before_script:
  - bundle exec sidekiq -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log &
  - sleep 1
services:
  - redis-server
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.17.0